# Setup
title:               臺北市水土保持技師公會
tagline:             '直播網站'
description:         '暫時建構工程中'
url:                 http://tpswcpea.netlify.app
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Steven Huang 
  url:               https://www.linkedin.com/in/steven-huang/
  email:             spring28892@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
